export default [
  {
    id: 1,
    field: "Regulatory Model Name",
    type: "text",
    required: false,
  },
  {
    id: 2,
    field: "Product Name",
    type: "text",
    required: true,
  },
  {
    id: 3,
    field: "Product Family",
    type: "text",
    required: true,
  },
  {
    id: 4,
    field: "Product Category",
    type: "dropdown/auto",
    required: true,
  },
  {
    id: 5,
    field: "Product Description / Intended Use",
    type: "text",
    required: false,
  },
  {
    id: 6,
    field: "Model Difference (if applicable)",
    type: "text",
    required: false,
  },
  {
    id: 7,
    field: "Intended Environment",
    type: "radio",
    required: true,
    radioOptions: ["Household", "Commercial Clinical"],
  },
  {
    id: 8,
    field: "Applicable Standards",
    type: "dropdown/text",
    required: true,
  },
  {
    id: 9,
    field: "Applicant Name and Address",
    type: "text",
    required: false,
  },
  {
    id: 10,
    field: "Manufacturer Name and Address",
    type: "text/extra",
    required: false,
  },
  {
    id: 11,
    field: "TradeMark",
    type: "radio",
    required: false,
    radioOptions: ["Yes", "No"],
  },
  {
    id: 12,
    field: "TradeMark",
    type: "upload",
    required: false,
    optional: true,
  },
  {
    id: 13,
    field: "Family/Series Model",
    type: "text/extra",
    required: false,
  },
  {
    id: 14,
    field: "Market",
    type: "",
    required: false,
  },
];
