export const generalProdInfo = [
  {
    id: 1,
    field: "Regulatory Model Name",
    placeholder: "Enter Model Name",
    type: "text",
    required: false,
  },
  {
    id: 2,
    field: "Product Name",
    placeholder: "Enter Product Name",
    type: "text",
    required: true,
  },
  {
    id: 3,
    field: "Product Family",
    placeholder: "Enter Product Family",
    type: "text",
    required: true,
  },
  {
    id: 4,
    field: "Product Category",
    type: "categoryInput",
    required: true,
  },
  {
    id: 5,
    field: "Product Description / Intended Use",
    placeholder: "Enter Product Description / Intended Use",
    type: "text",
    required: false,
  },
  {
    id: 6,
    field: "Model Difference (if applicable)",
    placeholder: "Enter Model Difference",
    type: "text",
    required: false,
  },
  {
    id: 7,
    field: "Intended Environment",
    type: "checkbox",
    required: true,
    options: ["Household", "Commercial", "Clinical"],
  },
  {
    id: 8,
    field: "Applicable Standards",
    type: "applicableStandards",
    required: true,
  },
  {
    id: 9,
    field: "Applicant Name and Address",
    placeholder: "Enter Applicant Name and Address",
    type: "text",
    required: false,
  },
  {
    id: 10,
    field: "Manufacturer Name and Address",
    placeholder: "Enter Name and Address",
    type: "text/extra",
    required: false,
  },
  {
    id: 11,
    field: "TradeMark",
    type: "radio/upload",
    required: false,
    options: ["Yes", "No"],
  },
  {
    id: 12,
    field: "Family/Series Model",
    placeholder: "Enter Family/Series Model",
    type: "text/extra",
    required: false,
  },
  {
    id: 13,
    field: "Market",
    type: "autocomplete/sections",
    placeholder: "Select a country",
    required: false,
  },
];

export const prodTechInfo = [
  {
    id: 1,
    field: "Overall Size of Equipment (W x D x H)",
    placeholder: "Enter Size",
    type: "text",
    required: false,
  },
  {
    id: 2,
    field: "Power Rating/Electrical Rating",
    placeholder: "Select Rating",
    type: "autocomplete",
    required: false,
    options: ["Voltage", "Phase", "Frequency", "Power", "Current"],
  },
  {
    id: 3,
    field: "Operation Mode",
    type: "radio/text",
    required: false,
    options: ["Continuons", "Duty Cycle"],
  },
  {
    id: 4,
    field: "Classification of use by",
    placeholder: "Select Classification",
    type: "autocomplete",
    required: false,
    options: [
      "Ordinary person",
      "Children likely present",
      "Instructed person",
      "Skilled person",
    ],
  },
  {
    id: 5,
    field: "Supply Connection",
    placeholder: "Select Supply connection",
    type: "autocomplete",
    required: false,
    options: ["AC mains", "DC mains", "Battery Powered"],
  },
  {
    id: 6,
    field: "Supply Connection – Type",
    placeholder: "Select Type",
    type: "autocomplete/categories/free",
    required: false,
    options: [
      {
        category: "Pluggable equipment type A",
        values: [
          "Non-detachable Supply Cord",
          "Appliance Coupler",
          "Direct plug-in",
        ],
      },
      {
        category: "Pluggable equipment type B",
        values: ["Non-detachable Supply Cord", "Appliance Coupler"],
      },
      {
        category: "Other",
        values: ["Permanent connection", "Mating connector "],
      },
    ],
  },
  {
    id: 7,
    field: "Equipment Mobility",
    placeholder: "Select Equipment Mobility",
    type: "autocomplete",
    required: false,
    options: [
      "Movable",
      "Hand-held",
      "Transportable",
      "Direct plug-in",
      "Stationary for building-in",
      "Wall/ceiling-mounted SRME/rack-mounted",
      "Other",
    ],
  },
];

export const prodEnvInfo = [
  {
    id: 1,
    field: "Polution Degree",
    placeholder: "Enter Polution Degree",
    type: "radio",
    required: false,
    options: ["PD1", "PD2", "PD3"],
  },
  {
    id: 2,
    field: "Manufacturer Specific Max Operating Ambient",
    placeholder: "Enter Ambient",
    type: "text/celcius",
    required: false,
  },
  {
    id: 3,
    field: "Ingree Protection Classification",
    placeholder: "Enter Classification",
    type: "text/numericWithX",
    required: false,
  },
  {
    id: 4,
    field: "Altitude During Operation",
    placeholder: "Enter Classification",
    type: "text",
    required: false,
  },
  {
    id: 5,
    field: "Mass Of Equipment (in kg)",
    placeholder: "Enter Mass",
    type: "text/numericDecimals",
    required: false,
  },
  {
    id: 6,
    field: "Relative Humidity (%)",
    placeholder: "Enter Classification",
    type: "text",
    required: false,
  },
  {
    id: 7,
    field: "Atmospheric Pressure [kPa]",
    placeholder: "Enter Classification",
    type: "text",
    required: false,
  },
  {
    id: 8,
    field: "Indoor or Outdoor",
    placeholder: "Enter Classification",
    type: "checkbox",
    required: false,
    options: ["Indoor", "Outdoor"],
  },
];

export const markingDoc = [
  {
    id: 1,
    field: "Copy of Marking Plate",
    type: "upload",
    uploadLabel: "copy-or-marking-plate",
    required: false,
  },
  {
    id: 2,
    field: "Warning/Cautionary Marking",
    type: "upload",
    uploadLabel: "warning-cautionary-marking",
    required: false,
  },
  {
    id: 3,
    field: "Polution Degree",
    placeholder: "Fuse Type",
    type: "radio",
    required: false,
    options: ["Replaceable", "Non-Replaceable", "None"],
  },
  {
    id: 4,
    field: "Fuse Marking",
    placeholder: "Enter Model Name",
    type: "text",
    required: false,
  },
];
